// Copyright (c) 2016-2026 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.sbtplugin

import org.typelevel.sbt.gha.GenerativePlugin
import sbt.*

/**
 * One check to require in branch protection, in place of one entry per test shard, JDK and Scala
 * version.
 *
 * GitHub matches a required check by its literal name, built from the job name plus its matrix
 * values: `Test (ubuntu-22.04, 3, temurin@25, 0)`. Listing those is fragile twice over. Change a
 * JDK, a Scala version, a shard count or a job name and the entry silently stops matching. And a
 * job skipped by a job-level condition never expands its matrix, so it reports under the bare job
 * name and a pull request requiring the matrixed one waits forever.
 *
 * This job depends on jobs by id through `needs`, which carry none of those values, and fails if
 * any of them failed. Require it and nothing else.
 *
 * Generated by default. It is inert until someone points branch protection at it, but it reports
 * from the first push, which is what makes it selectable in GitHub's picker.
 */
object LucumaRequiredChecksPlugin extends AutoPlugin {

  import GenerativePlugin.autoImport.*

  object autoImport {

    lazy val lucumaRequiredChecks = settingKey[Boolean](
      "Generate the aggregating job to require in branch protection (default: true)"
    )

    lazy val lucumaRequiredCheckJobs = settingKey[Seq[String]](
      "Ids of the jobs to require; each is validated against the generated workflow"
    )

    lazy val lucumaRequiredChecksJobName = settingKey[String](
      "Display name of the generated job; GitHub appends the matrix values to form the check name"
    )

    /** Id of the generated job. */
    val lucumaRequiredChecksJobId: String = "required-checks"
  }

  import autoImport.*

  // LucumaAffectedPlugin is listed for ordering only, not for anything it provides. Both plugins
  // append jobs to githubWorkflowGeneratedCI, and this one must see the final list to validate ids
  // against it. Since LucumaAffectedPlugin already activates wherever LucumaPlugin does, this
  // changes nothing about where this plugin is active.
  override def requires: Plugins = LucumaPlugin && LucumaAffectedPlugin

  override def trigger: PluginTrigger = allRequirements

  override val buildSettings: Seq[Setting[?]] = Seq(
    lucumaRequiredChecks        := true,
    lucumaRequiredCheckJobs     := Seq("build"),
    lucumaRequiredChecksJobName := "REQUIRED CHECKS FOR BRANCH PROTECTION - AGGREGATED",
    githubWorkflowGeneratedCI   := {
      val jobs = githubWorkflowGeneratedCI.value
      if (!lucumaRequiredChecks.value) jobs
      else {
        val required = lucumaRequiredCheckJobs.value.distinct
        // a typo or a renamed job would otherwise drop a requirement in silence, and you would
        // find out from a pull request that merged when it should not have
        val missing  = required.filterNot(id => jobs.exists(_.id == id))
        if (missing.nonEmpty)
          sys.error(
            s"lucumaRequiredCheckJobs names jobs that do not exist: ${missing.mkString(", ")}. " +
              s"Known jobs: ${jobs.map(_.id).mkString(", ")}"
          )
        if (required.isEmpty) jobs
        else jobs :+ aggregate(lucumaRequiredChecksJobName.value, required)
      }
    }
  )

  private def aggregate(name: String, required: Seq[String]): WorkflowJob =
    WorkflowJob(
      id = lucumaRequiredChecksJobId,
      name = name,
      steps = List(
        WorkflowStep.Run(
          List("""echo "::error::a required job did not pass"""", "exit 1"),
          name = Some("Fail if a required job did not pass"),
          // `skipped` is deliberately not a failure: a job the diff made pointless is fine
          cond =
            Some("contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')")
        ),
        WorkflowStep.Run(
          List(s"""echo "all of ${required.mkString(", ")} passed or were skipped""""),
          name = Some("Report success")
        )
      ),
      sbtStepPreamble = Nil,
      // `always()` so a skipped dependency doesn't skip the gate, which would leave the required
      // check unreported -- the very failure this job exists to prevent
      cond = Some("always()"),
      needs = required.toList,
      // `ubuntu-latest` rather than a pinned image: sbt-typelevel always renders `runs-on` from
      // the matrix, so the OS lands in the check name, and this label never changes
      oses = List("ubuntu-latest"),
      scalas = Nil,
      javas = Nil
    )
}
