// Copyright (c) 2016-2026 Association of Universities for Research in Astronomy, Inc. (AURA)
// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause

package lucuma.sbtplugin

import org.typelevel.sbt.TypelevelKernelPlugin
import org.typelevel.sbt.gha.GenerativePlugin
import sbt.*
import sbt.Keys.*

import scala.io.Source

/**
 * Posts to Slack when a workflow fails on the default branch.
 *
 * GitHub only notifies the actor who triggered a run, and merges are pushed by a bot, so a red
 * `main` reaches nobody. This watches whole workflows rather than instrumenting jobs, so a job
 * added later is covered without touching anything.
 *
 * sbt-typelevel only generates `ci.yml` and `clean.yml`, so the file is written by a task of our
 * own, checked in CI the same way the shared scalafmt and scalafix configs are.
 *
 * On by default. Add the webhook as a repository or organization secret; without it the workflow
 * warns and does nothing, rather than failing on top of the failure it was reporting.
 */
object LucumaSlackPlugin extends AutoPlugin {

  import GenerativePlugin.autoImport.*
  import TypelevelKernelPlugin.autoImport.*

  object autoImport {

    lazy val lucumaSlackNotify = settingKey[Boolean](
      "Generate a workflow that posts to Slack when CI fails on the default branch (default: true)"
    )

    lazy val lucumaSlackNotifyWorkflows = settingKey[Seq[String]](
      "Names of the workflows to watch (default: just sbt-typelevel's `Continuous Integration`)"
    )

    lazy val lucumaSlackNotifyBranch = settingKey[String](
      "Branch whose failures are reported (default: main)"
    )

    lazy val lucumaSlackWebhookSecret = settingKey[String](
      "Name of the Actions secret holding the Slack webhook URL (default: GPP_SLACK_WEBHOOK_URL)"
    )

    lazy val lucumaSlackNotifyGenerate = taskKey[Unit](
      "Write the Slack notification workflow"
    )

    lazy val lucumaSlackNotifyCheck = taskKey[Unit](
      "Fail if the Slack notification workflow is missing or out of date"
    )
  }

  import autoImport.*

  override def requires: Plugins = LucumaPlugin

  override def trigger: PluginTrigger = allRequirements

  private val workflowFile = "ci-failure-slack.yml"

  override val buildSettings: Seq[Setting[_]] = Seq(
    lucumaSlackNotify           := true,
    lucumaSlackNotifyWorkflows  := Seq("Continuous Integration"),
    lucumaSlackNotifyBranch     := "main",
    lucumaSlackWebhookSecret    := "GPP_SLACK_WEBHOOK_URL",
    lucumaSlackNotifyGenerate   := {
      val target   = workflowPath.value
      val expected = contents.value
      val log      = streams.value.log
      if (lucumaSlackNotify.value) {
        IO.write(target, expected)
        log.info(s"Wrote $target")
      } else if (target.exists) {
        IO.delete(target)
        log.info(s"Deleted $target (lucumaSlackNotify is false)")
      }
    },
    lucumaSlackNotifyCheck      := {
      val target   = workflowPath.value
      val expected = contents.value
      if (lucumaSlackNotify.value) {
        if (!target.exists)
          sys.error(s"$target is missing; run lucumaSlackNotifyGenerate")
        val actual = {
          val src = Source.fromFile(target)
          try src.mkString
          finally src.close()
        }
        if (actual != expected)
          sys.error(s"$target is out of date; run lucumaSlackNotifyGenerate")
      } else if (target.exists)
        sys.error(s"$target exists but lucumaSlackNotify is false; run lucumaSlackNotifyGenerate")
    },
    // checked alongside the other generated configs, so drift fails the build
    githubWorkflowBuild         := githubWorkflowBuild.value.map {
      case step: WorkflowStep.Sbt
          if lucumaSlackNotify.value && step.name.exists(_.contains("Check headers")) =>
        step.withCommands(step.commands :+ "lucumaSlackNotifyCheck")
      case step => step
    },
    // regenerated by `prePR` and by Steward, like the shared scalafmt and scalafix configs
    GlobalScope / tlCommandAliases ~= { aliases =>
      List("prePR", "tlPrePrBotHook").foldLeft(aliases) { (acc, alias) =>
        acc.get(alias).fold(acc)(cmds => acc + (alias -> (cmds :+ "lucumaSlackNotifyGenerate")))
      }
    }
  )

  private lazy val workflowPath =
    Def.setting((ThisBuild / baseDirectory).value / ".github" / "workflows" / workflowFile)

  private lazy val contents = Def.setting {
    val workflows = lucumaSlackNotifyWorkflows.value.mkString(", ")
    val branch    = lucumaSlackNotifyBranch.value
    val secret    = lucumaSlackWebhookSecret.value
    val e         = "$" + "{{" // GitHub expression syntax collides with Scala interpolation

    s"""|# Generated by sbt-lucuma's lucumaSlackNotifyGenerate. Do not edit by hand; change the
        |# `lucumaSlackNotify*` settings in build.sbt and regenerate.
        |#
        |# GitHub only notifies the actor who triggered a run, and merges are pushed by a bot, so a
        |# red `$branch` would otherwise reach nobody. Watching whole workflows means jobs added
        |# later are covered without touching this file.
        |name: CI Failure Notification
        |
        |on:
        |  workflow_run:
        |    workflows: [$workflows]
        |    types: [completed]
        |    branches: [$branch]
        |
        |permissions:
        |  actions: read
        |  contents: read
        |
        |jobs:
        |  notify:
        |    name: Notify Slack
        |    if: $e github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out' }}
        |    runs-on: ubuntu-22.04
        |    steps:
        |      # Best effort, and deliberately tolerant: a transient API failure here must not cost
        |      # us the notification, which is the whole point of this workflow.
        |      - name: Collect failed jobs
        |        id: failed
        |        continue-on-error: true
        |        env:
        |          GH_TOKEN: $e secrets.GITHUB_TOKEN }}
        |        run: |
        |          set -uo pipefail
        |          jobs=$$(gh api --paginate \\
        |            "repos/$e github.repository }}/actions/runs/$e github.event.workflow_run.id }}/jobs" \\
        |            -q '.jobs[] | select(.conclusion == "failure" or .conclusion == "timed_out") | .name' \\
        |            | paste -sd ', ' - || true)
        |          echo "jobs=$${jobs:-unknown}" >> "$$GITHUB_OUTPUT"
        |
        |      - name: Post to Slack
        |        env:
        |          $secret: $e secrets.$secret }}
        |          FAILED_JOBS: $e steps.failed.outputs.jobs }}
        |          RUN_URL: $e github.event.workflow_run.html_url }}
        |          HEAD_SHA: $e github.event.workflow_run.head_sha }}
        |          ACTOR: $e github.event.workflow_run.actor.login }}
        |          WORKFLOW: $e github.event.workflow_run.name }}
        |          CONCLUSION: $e github.event.workflow_run.conclusion }}
        |        run: |
        |          set -euo pipefail
        |          if [ -z "$${$secret:-}" ]; then
        |            echo "::warning::$secret is not set; skipping the Slack notification"
        |            exit 0
        |          fi
        |          text=$$(printf ':x: *%s* %s %s on `%s`\\n*Failed:* %s\\n*Commit:* `%s` (%s)\\n%s' \\
        |            "$e github.repository }}" "$$WORKFLOW" "$$CONCLUSION" "$branch" \\
        |            "$${FAILED_JOBS:-unknown}" "$${HEAD_SHA:0:8}" "$$ACTOR" "$$RUN_URL")
        |          jq -n --arg text "$$text" '{text: $$text}' \\
        |            | curl -sS --fail-with-body -X POST -H 'Content-type: application/json' --data @- "$$$secret"
        |""".stripMargin
  }
}
